# Generated by Django 3.0.4 on 2020-03-13 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Location')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates of Location')),
                ('address', models.CharField(max_length=100, verbose_name='Address of Location')),
                ('zip_code', models.CharField(max_length=9, verbose_name='Zip code of Location')),
                ('city', models.CharField(max_length=100, verbose_name='City of Location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['address'],
                'permissions': (('detail_location', 'Can detail Location'), ('list_location', 'Can list Location')),
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('location',), name='unique_location'),
        ),
    ]
