# Generated by Django 3.0.4 on 2020-03-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('location', '0001_initial'),
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Order Name')),
                ('description', models.CharField(max_length=250, verbose_name='Order Description')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Update date')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_location_destiny', to='location.Location', verbose_name='Destiny Location')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driver.Driver', verbose_name='Order Driver')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_location_origin', to='location.Location', verbose_name='Origin Location')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='truck.Truck', verbose_name='Order Truck')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['id'],
                'permissions': (('detail_order', 'Can detail Order'), ('list_order', 'Can list Order')),
            },
        ),
    ]
